<a href="https://colab.research.google.com/github/D6342/D1978/blob/main/P1b_Program_to_solve_the_XOR_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

# Build model
model = Sequential()
model.add(Dense(units=2, activation='relu', input_dim=2))
model.add(Dense(units=1, activation='sigmoid'))

# Compile with metrics in a list
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# XOR data
X = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
print("Input data:")
print(X)

y = np.array([0., 1., 1., 0.])
print("\nTarget labels:")
print(y)

# Train model
model.fit(X, y, epochs=500, verbose=0)

# Predict
predictions = model.predict(X)
print("\nPredictions after training:")
print(predictions)


Input data:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]

Target labels:
[0. 1. 1. 0.]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

Predictions after training:
[[0.44913948]
 [0.4491306 ]
 [0.65454435]
 [0.44919714]]
