<a href="https://colab.research.google.com/github/D6342/D1978/blob/main/P3b_Using_a_deep_feed_forward_network_with_two_hidden_layers_for_performing_multiclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/flower_1.csv")

In [ ]:
df.head()

sepal length  sepal width  petal length  petal width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
x=df.iloc[:,:-1].astype(float)
y=df.iloc[:,-1]

In [ ]:
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
import numpy as np
from tensorflow.keras.utils import to_categorical
#from keras.utils import np_utils
encoded_Y = to_categorical(y)
encoded_Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
#creating a model
model = Sequential()

model.add(Dense(units = 10, activation = 'relu', input_dim = 4))
model.add(Dense(units = 8, activation = 'relu'))
model.add(Dense(units = 3, activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.fit(x,encoded_Y,epochs = 400,batch_size = 10)

Epoch 1/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3315 - loss: 0.9902
Epoch 2/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6821 - loss: 0.8806 
Epoch 3/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8620 - loss: 0.8583 
Epoch 4/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8839 - loss: 0.8134 
Epoch 5/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8580 - loss: 0.7757 
Epoch 6/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8730 - loss: 0.7530 
Epoch 7/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9060 - loss: 0.7202 
Epoch 8/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9087 - loss: 0.6825 
Epoch 9/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8612 - loss: 0.6748 
Epoch 10/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8795 - loss: 0.6285 
Epoch 11/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8386 - loss: 0.6065 
Epoch 12/400
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step -

In [ ]:
predict = model.predict(x)
print(predict)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[[9.99985993e-01 1.39600561e-05 2.19506433e-13]
 [9.99972045e-01 2.78778043e-05 1.09469866e-12]
 [9.99966562e-01 3.33710668e-05 1.55530536e-12]
 [9.99945581e-01 5.43967944e-05 5.23782970e-12]
 [9.99983728e-01 1.61697444e-05 3.05058550e-13]
 [9.99987066e-01 1.29257260e-05 2.06020300e-13]
 [9.99949515e-01 5.04803429e-05 4.12898752e-12]
 [9.99979675e-01 2.03037689e-05 5.43798567e-13]
 [9.99918163e-01 8.17307300e-05 1.27962016e-11]
 [9.99975979e-01 2.39332749e-05 8.07589943e-13]
 [9.99992311e-01 7.57829548e-06 5.64569143e-14]
 [9.99965727e-01 3.42041712e-05 1.87225842e-12]
 [9.99972284e-01 2.77110830e-05 1.08264092e-12]
 [9.99945462e-01 5.45198236e-05 4.39925093e-12]
 [9.99997914e-01 2.00911154e-06 2.33314103e-15]
 [9.99995768e-01 4.20286551e-06 1.40465058e-14]
 [9.99991715e-01 8.19174238e-06 6.03268046e-14]
 [9.99982774e-01 1.72181353e-05 3.53221006e-13]
 [9.99993980e-01 6.01938609e-06 3.63742206e-14]
 [9.99983609e-01 1.62732049e-05 3.19766891e-13]
 [

In [ ]:
for i in range(35,150,3):
    print(predict[i],encoded_Y[i])

[9.9998373e-01 1.6157474e-05 2.8385652e-13] [1. 0. 0.]
[9.9993104e-01 6.8895912e-05 8.2201902e-12] [1. 0. 0.]
[9.9989682e-01 1.0316418e-04 2.1461461e-11] [1. 0. 0.]
[9.9996823e-01 3.1669864e-05 1.7572324e-12] [1. 0. 0.]
[9.9995404e-01 4.5854289e-05 3.3647369e-12] [1. 0. 0.]
[5.6588374e-06 9.9986601e-01 1.2853478e-04] [0. 1. 0.]
[7.8478850e-05 9.8627263e-01 1.3648926e-02] [0. 1. 0.]
[2.7384116e-05 9.8564917e-01 1.4323396e-02] [0. 1. 0.]
[1.2315116e-04 9.8726058e-01 1.2616343e-02] [0. 1. 0.]
[1.7517497e-05 9.9986672e-01 1.1584285e-04] [0. 1. 0.]
[9.165279e-06 9.999017e-01 8.900657e-05] [0. 1. 0.]
[4.1558294e-05 8.1818354e-01 1.8177490e-01] [0. 1. 0.]
[2.10892595e-05 9.99873877e-01 1.04969404e-04] [0. 1. 0.]
[1.3020944e-05 9.9983549e-01 1.5158682e-04] [0. 1. 0.]
[2.0566060e-05 8.3832943e-01 1.6164997e-01] [0. 1. 0.]
[4.2561609e-05 9.9965304e-01 3.0444181e-04] [0. 1. 0.]
[5.296969e-06 6.960567e-02 9.303890e-01] [0. 1. 0.]
[1.2753556e-05 9.9793231e-01 2.0549404e-03] [0. 1. 0.]
[6.9090667e-0

In [ ]:
actual = []

for i in range(0,150):
    actual.append(np.argmax(predict[i]))

print(actual)

[np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1)

In [ ]:
newdf = pd.DataFrame(list(zip(actual,y)),columns = ['Actual','Predicted'])
newdf

Actual  Predicted
0         0          0
1         0          0
2         0          0
3         0          0
4         0          0
..      ...        ...
145       2          2
146       2          2
147       2          2
148       2          2
149       2          2

[150 rows x 2 columns]